// Code generated by protoc-gen-go.
// source: dfss/net/fixtures/test.proto
// DO NOT EDIT!

/*
Package fixtures is a generated protocol buffer package.

It is generated from these files:
	dfss/net/fixtures/test.proto

It has these top-level messages:
	Hop
	IsAuth
	Empty
*/
package fixtures

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Hop struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *Hop) Reset()                    { *m = Hop{} }
func (m *Hop) String() string            { return proto.CompactTextString(m) }
func (*Hop) ProtoMessage()               {}
func (*Hop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type IsAuth struct {
	Auth bool `protobuf:"varint,1,opt,name=auth" json:"auth,omitempty"`
}

func (m *IsAuth) Reset()                    { *m = IsAuth{} }
func (m *IsAuth) String() string            { return proto.CompactTextString(m) }
func (*IsAuth) ProtoMessage()               {}
func (*IsAuth) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Hop)(nil), "fixtures.Hop")
	proto.RegisterType((*IsAuth)(nil), "fixtures.IsAuth")
	proto.RegisterType((*Empty)(nil), "fixtures.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for Test service

type TestClient interface {
	Ping(ctx context.Context, in *Hop, opts ...grpc.CallOption) (*Hop, error)
	Auth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IsAuth, error)
}

type testClient struct {
	cc *grpc.ClientConn
}

func NewTestClient(cc *grpc.ClientConn) TestClient {
	return &testClient{cc}
}

func (c *testClient) Ping(ctx context.Context, in *Hop, opts ...grpc.CallOption) (*Hop, error) {
	out := new(Hop)
	err := grpc.Invoke(ctx, "/fixtures.Test/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testClient) Auth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*IsAuth, error) {
	out := new(IsAuth)
	err := grpc.Invoke(ctx, "/fixtures.Test/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Test service

type TestServer interface {
	Ping(context.Context, *Hop) (*Hop, error)
	Auth(context.Context, *Empty) (*IsAuth, error)
}

func RegisterTestServer(s *grpc.Server, srv TestServer) {
	s.RegisterService(&_Test_serviceDesc, srv)
}

func _Test_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hop)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fixtures.Test/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).Ping(ctx, req.(*Hop))
	}
	return interceptor(ctx, in, info, handler)
}

func _Test_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fixtures.Test/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).Auth(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Test_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fixtures.Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Test_Ping_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _Test_Auth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x49, 0x49, 0x2b, 0x2e,
	0xd6, 0xcf, 0x4b, 0x2d, 0xd1, 0x4f, 0xcb, 0xac, 0x28, 0x29, 0x2d, 0x4a, 0x2d, 0xd6, 0x2f, 0x49,
	0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0x09, 0x2a, 0x09, 0x72, 0x31,
	0x7b, 0xe4, 0x17, 0x08, 0x71, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x2a,
	0x89, 0x71, 0xb1, 0x79, 0x16, 0x3b, 0x96, 0x96, 0x64, 0x08, 0xf1, 0x70, 0xb1, 0x24, 0x02, 0x69,
	0xb0, 0x38, 0x87, 0x12, 0x3b, 0x17, 0xab, 0x6b, 0x6e, 0x41, 0x49, 0xa5, 0x51, 0x34, 0x17, 0x4b,
	0x08, 0xd0, 0x2c, 0x21, 0x35, 0x2e, 0x96, 0x80, 0xcc, 0xbc, 0x74, 0x21, 0x5e, 0x3d, 0x98, 0x71,
	0x7a, 0x40, 0xb3, 0xa4, 0x50, 0xb9, 0x4a, 0x0c, 0x42, 0xda, 0x5c, 0x2c, 0x60, 0xe3, 0xf8, 0x11,
	0x12, 0x60, 0x83, 0xa4, 0x04, 0x10, 0x02, 0x10, 0x1b, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0x2e, 0x34,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x7b, 0x0d, 0xb5, 0xc1, 0x00, 0x00, 0x00,
}
